version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ElectronicShop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  spring_app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ElectronicShop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  react_app:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"

volumes:
  postgres_data: