spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://localhost:5432/ElectronicShop
        username: postgres
        password: postgres
    jpa:
        hibernate: 
            ddl-auto: none

server:
  servlet:
    context-path: "/api/"
