spring:
    application:
        name: backend
    datasource:
        url: jdbc:postgresql://localhost:5432/ElectronicShop
        username: postgres
        password: postgres
    jpa:
        hibernate: 
            ddl-auto: none
    flyway:
        baseline-on-migrate: true

minio:
    url: http://127.0.0.1:9000
    access-key: minioadmin
    secret-key: minioadmin

server:
  servlet:
    context-path: "/api/"
